; PartsManager API Server Configuration

[ConnectionStrings]
DefaultConnection=Data Source=C:/SourceCode/CS/PartsManager/DB/Parts.db

[Network]
Urls=http://0.0.0.0:5000

[System]
Language=de
AttachmentPath=Attachments
